### PR TITLE
Include legacy.js in the list of files to publish

### PR DESCRIPTION
**Pull request by boudra**
This file is needed by `browser.js`

### CODE REVIEW

**Comment by odarriba** [comment]
LGTM 🚀

**Comment by bigardone** [comment]
LGTM 🤘 🚀

**Comment by gilacost** [comment]
😴 ?

**Comment by pilu** [comment]
LGTM :eyeglasses:

**Comment by customcommander** [comment]
jenkins

Please guys :-)

**Comment by ishantmehta01** [comment]
Please merge this soon. Its breaking out builds.
LGTM. 👍

**Comment by gilacost** [comment]
🙌

**Pull request merged**
