### PR TITLE
1shot

### PR DESCRIPTION
**Pull request by fanatid**
@dcousens JFYI, this PR do not remove `readable-stream` package, because it package also required by `create-hash` -> `cipher-base`. If we want remove `readable-stream` from `bitcoinjs-lib` bundle (reduce 40kb) we also should create 1shot in `createHash`.
Thoughts?

### CODE REVIEW

**Comment by fanatid** [comment]
Right now close, because without `createHash/1shot` doesn't make sense.

**Comment by calvinmetcalf** [comment]
the hashing stuff is actually in [sha.js](https://github.com/crypto-browserify/sha.js) which I don't believe has any streams stuff in it, so you might be better off making a hmac lib that goes directly to sha.js

**Comment by fanatid** [comment]
yea, probably it will better, but `bitcoinjs-lib` also need `ripemd160`
and I even not sure that it all make sense for sake of 40kb

**Comment by dcousens** [comment]
> not sure that it all make sense for sake of 40kb

It might just be easier to find ways to reduce `readable-streams` foot print.
It really shouldn't be 40kb...

**Comment by dcousens** [comment]
ping @calvinmetcalf ? :P

**Comment by calvinmetcalf** [comment]
it's not readable-streams its browserify streams which I is based on readable-streams so I don't know what version of readable streams its on, some of that include other browserify libs like events and buffers which are likely also being included by other things.

**Comment by fanatid** [comment]
@dcousens I can create package `crypto1shot` which will include ciphers/hashes/hmac if you agree add this to `bitcoinjs-lib`, also in this way we can save more than 40kb, because don't need all `sha.js`

**Comment by dcousens** [comment]
@fanatid there is also the point that,  in production,  I often find myself using streams anyway so,  for me,  using `crypto1shot` would actually increase my bundle size...

**Pull request closed without merging**
